name: Deploy DEV

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: databricks/setup-cli@main
      - run: databricks bundle validate -t dev
      - run: databricks bundle deploy -t dev
    env:
      DATABRICKS_HOST: ${{ secrets.DEV_DATABRICKS_HOST }}
      DATABRICKS_CLIENT_ID: ${{ secrets.DEV_CLIENT_ID }}
      DATABRICKS_CLIENT_SECRET: ${{ secrets.DEV_CLIENT_SECRET }}
